# Generated by Django 3.2.13 on 2022-12-05 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agroup', models.IntegerField(default=0, null=True)),
                ('leave_city', models.CharField(max_length=100, null=True)),
                ('arrive_city', models.CharField(max_length=100, null=True)),
                ('leave_station', models.CharField(max_length=100, null=True)),
                ('arrive_station', models.CharField(max_length=100, null=True)),
                ('leave_time', models.DateTimeField(null=True)),
                ('arrive_time', models.DateTimeField(null=True)),
                ('high_capacity', models.IntegerField(default=0, null=True)),
                ('middle_capacity', models.IntegerField(default=0, null=True)),
                ('low_capacity', models.IntegerField(default=0, null=True)),
                ('high_price', models.FloatField(default=0, null=True)),
                ('middle_price', models.FloatField(default=0, null=True)),
                ('low_price', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
